# -*- coding: utf-8 -*-
"""
The IMDb Top 250 — 250 of the most acclaimed and widely known films.

Each entry: (title, year, director)

Source: the IMDb Top 250 chart (a rating- and popularity-weighted ranked
list), via the community snapshot at github.com/movie-monk-b0t/top250.
Entries are ordered by IMDb rating (highest first).

Two cleanups were applied to the raw data:
  * Foreign-language films are given their well-known English titles
    (e.g. Gisaengchung -> Parasite, Shichinin no samurai -> Seven Samurai).
  * Years are the canonical original-release year (matching the year IMDb
    displays). The raw snapshot sometimes used the later wide/US-release
    year; those were corrected (e.g. Casablanca 1943 -> 1942).
"""

MOVIES = [
    ("The Shawshank Redemption", 1994, "Frank Darabont"),
    ("The Godfather", 1972, "Francis Ford Coppola"),
    ("The Lord of the Rings: The Return of the King", 2003, "Peter Jackson"),
    ("The Godfather Part II", 1974, "Francis Ford Coppola"),
    ("The Dark Knight", 2008, "Christopher Nolan"),
    ("Schindler's List", 1994, "Steven Spielberg"),
    ("12 Angry Men", 1957, "Sidney Lumet"),
    ("Pulp Fiction", 1994, "Quentin Tarantino"),
    ("Jai Bhim", 2021, "T.J. Gnanavel"),
    ("The Lord of the Rings: The Two Towers", 2002, "Peter Jackson"),
    ("The Lord of the Rings: The Fellowship of the Ring", 2001, "Peter Jackson"),
    ("Inception", 2010, "Christopher Nolan"),
    ("The Good, the Bad and the Ugly", 1966, "Sergio Leone"),
    ("Forrest Gump", 1994, "Robert Zemeckis"),
    ("Fight Club", 1999, "David Fincher"),
    ("The Matrix", 1999, "Lana Wachowski & Lilly Wachowski"),
    ("The Empire Strikes Back", 1980, "Irvin Kershner"),
    ("One Flew Over the Cuckoo's Nest", 1975, "Milos Forman"),
    ("Goodfellas", 1990, "Martin Scorsese"),
    ("The Silence of the Lambs", 1991, "Jonathan Demme"),
    ("The Green Mile", 1999, "Frank Darabont"),
    ("Terminator 2: Judgment Day", 1991, "James Cameron"),
    ("Star Wars", 1977, "George Lucas"),
    ("Seven Samurai", 1954, "Akira Kurosawa"),
    ("Harakiri", 1962, "Masaki Kobayashi"),
    ("Spirited Away", 2001, "Hayao Miyazaki"),
    ("Se7en", 1995, "David Fincher"),
    ("Saving Private Ryan", 1998, "Steven Spielberg"),
    ("Life Is Beautiful", 1997, "Roberto Benigni"),
    ("It's a Wonderful Life", 1946, "Frank Capra"),
    ("Interstellar", 2014, "Christopher Nolan"),
    ("City of God", 2002, "Fernando Meirelles & Kátia Lund"),
    ("Whiplash", 2014, "Damien Chazelle"),
    ("The Usual Suspects", 1995, "Bryan Singer"),
    ("The Prestige", 2006, "Christopher Nolan"),
    ("The Pianist", 2002, "Roman Polanski"),
    ("The Lion King", 1994, "Roger Allers & Rob Minkoff"),
    ("The Departed", 2006, "Martin Scorsese"),
    ("Rear Window", 1954, "Alfred Hitchcock"),
    ("Psycho", 1960, "Alfred Hitchcock"),
    ("Cinema Paradiso", 1988, "Giuseppe Tornatore"),
    ("Modern Times", 1936, "Charles Chaplin"),
    ("Léon: The Professional", 1994, "Luc Besson"),
    ("The Intouchables", 2011, "Olivier Nakache & Éric Toledano"),
    ("Grave of the Fireflies", 1988, "Isao Takahata"),
    ("Gladiator", 2000, "Ridley Scott"),
    ("Parasite", 2019, "Bong Joon Ho"),
    ("City Lights", 1931, "Charles Chaplin"),
    ("Casablanca", 1942, "Michael Curtiz"),
    ("Once Upon a Time in the West", 1968, "Sergio Leone"),
    ("Back to the Future", 1985, "Robert Zemeckis"),
    ("Apocalypse Now", 1979, "Francis Ford Coppola"),
    ("American History X", 1998, "Tony Kaye"),
    ("Alien", 1979, "Ridley Scott"),
    ("Witness for the Prosecution", 1957, "Billy Wilder"),
    ("WALL·E", 2008, "Andrew Stanton"),
    ("Top Gun: Maverick", 2022, "Joseph Kosinski"),
    ("The Shining", 1980, "Stanley Kubrick"),
    ("The Great Dictator", 1940, "Charles Chaplin"),
    ("The Dark Knight Rises", 2012, "Christopher Nolan"),
    ("High and Low", 1963, "Akira Kurosawa"),
    ("Like Stars on Earth", 2007, "Aamir Khan & Amole Gupte"),
    ("Sunset Blvd.", 1950, "Billy Wilder"),
    ("Spider-Man: Into the Spider-Verse", 2018, "Bob Persichetti & Peter Ramsey & Rodney Rothman"),
    ("Raiders of the Lost Ark", 1981, "Steven Spielberg"),
    ("Paths of Glory", 1957, "Stanley Kubrick"),
    ("Oldboy", 2003, "Park Chan-wook"),
    ("Princess Mononoke", 1997, "Hayao Miyazaki"),
    ("Memento", 2000, "Christopher Nolan"),
    ("Your Name", 2016, "Makoto Shinkai"),
    ("Joker", 2019, "Todd Phillips"),
    ("Come and See", 1985, "Elem Klimov"),
    ("Hamilton", 2020, "Thomas Kail"),
    ("Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", 1964, "Stanley Kubrick"),
    ("Django Unchained", 2012, "Quentin Tarantino"),
    ("The Lives of Others", 2006, "Florian Henckel von Donnersmarck"),
    ("Das Boot", 1981, "Wolfgang Petersen"),
    ("Coco", 2017, "Lee Unkrich & Adrian Molina"),
    ("Capernaum", 2018, "Nadine Labaki"),
    ("Braveheart", 1995, "Mel Gibson"),
    ("Avengers: Infinity War", 2018, "Anthony Russo & Joe Russo"),
    ("Avengers: Endgame", 2019, "Anthony Russo & Joe Russo"),
    ("American Beauty", 1999, "Sam Mendes"),
    ("Amadeus", 1984, "Milos Forman"),
    ("Aliens", 1986, "James Cameron"),
    ("3 Idiots", 2009, "Rajkumar Hirani"),
    ("Vertigo", 1958, "Alfred Hitchcock"),
    ("Up", 2009, "Pete Docter & Bob Peterson"),
    ("Toy Story 3", 2010, "Lee Unkrich"),
    ("Toy Story", 1995, "John Lasseter"),
    ("To Kill a Mockingbird", 1963, "Robert Mulligan"),
    ("The Sting", 1973, "George Roy Hill"),
    ("The Kid", 1921, "Charles Chaplin"),
    ("The Apartment", 1960, "Billy Wilder"),
    ("Star Wars: Episode VI - Return of the Jedi", 1983, "Richard Marquand"),
    ("Spider-Man: No Way Home", 2021, "Jon Watts"),
    ("Singin' in the Rain", 1952, "Stanley Donen & Gene Kelly"),
    ("Scarface", 1983, "Brian De Palma"),
    ("Reservoir Dogs", 1992, "Quentin Tarantino"),
    ("Requiem for a Dream", 2000, "Darren Aronofsky"),
    ("Pather Panchali", 1955, "Satyajit Ray"),
    ("Once Upon a Time in America", 1984, "Sergio Leone"),
    ("North by Northwest", 1959, "Alfred Hitchcock"),
    ("Metropolis", 1927, "Fritz Lang"),
    ("M", 1931, "Fritz Lang"),
    ("Amélie", 2001, "Jean-Pierre Jeunet"),
    ("Lawrence of Arabia", 1962, "David Lean"),
    ("Bicycle Thieves", 1948, "Vittorio De Sica"),
    ("Judgment at Nuremberg", 1961, "Stanley Kramer"),
    ("A Separation", 2011, "Asghar Farhadi"),
    ("The Hunt", 2012, "Thomas Vinterberg"),
    ("Inglourious Basterds", 2009, "Quentin Tarantino"),
    ("Incendies", 2010, "Denis Villeneuve"),
    ("Ikiru", 1952, "Akira Kurosawa"),
    ("Heat", 1995, "Michael Mann"),
    ("Good Will Hunting", 1997, "Gus Van Sant"),
    ("Full Metal Jacket", 1987, "Stanley Kubrick"),
    ("Eternal Sunshine of the Spotless Mind", 2004, "Michel Gondry"),
    ("Double Indemnity", 1944, "Billy Wilder"),
    ("Dangal", 2016, "Nitesh Tiwari"),
    ("Citizen Kane", 1941, "Orson Welles"),
    ("A Clockwork Orange", 1971, "Stanley Kubrick"),
    ("2001: A Space Odyssey", 1968, "Stanley Kubrick"),
    ("Yojimbo", 1961, "Akira Kurosawa"),
    ("Warrior", 2011, "Gavin O'Connor"),
    ("V for Vendetta", 2006, "James McTeigue"),
    ("Unforgiven", 1992, "Clint Eastwood"),
    ("Tokyo Story", 1953, "Yasujirô Ozu"),
    ("To Be or Not to Be", 1942, "Ernst Lubitsch"),
    ("There Will Be Blood", 2007, "Paul Thomas Anderson"),
    ("The Wolf of Wall Street", 2013, "Martin Scorsese"),
    ("The Truman Show", 1998, "Peter Weir"),
    ("The Treasure of the Sierra Madre", 1948, "John Huston"),
    ("The Thing", 1982, "John Carpenter"),
    ("The Sixth Sense", 1999, "M. Night Shyamalan"),
    ("The Great Escape", 1963, "John Sturges"),
    ("The Gold Rush", 1925, "Charles Chaplin"),
    ("The General", 1926, "Clyde Bruckman & Buster Keaton"),
    ("The Father", 2020, "Florian Zeller"),
    ("The Elephant Man", 1980, "David Lynch"),
    ("The Bridge on the River Kwai", 1957, "David Lean"),
    ("Taxi Driver", 1976, "Martin Scorsese"),
    ("Some Like It Hot", 1959, "Billy Wilder"),
    ("Snatch", 2000, "Guy Ritchie"),
    ("Shutter Island", 2010, "Martin Scorsese"),
    ("Sherlock Jr.", 1924, "Buster Keaton"),
    ("Rashomon", 1950, "Akira Kurosawa"),
    ("Ran", 1985, "Akira Kurosawa"),
    ("Raging Bull", 1980, "Martin Scorsese"),
    ("For a Few Dollars More", 1965, "Sergio Leone"),
    ("No Country for Old Men", 2007, "Ethan Coen & Joel Coen"),
    ("Monty Python and the Holy Grail", 1975, "Terry Gilliam & Terry Jones"),
    ("Lock, Stock and Two Smoking Barrels", 1998, "Guy Ritchie"),
    ("The Wages of Fear", 1953, "Henri-Georges Clouzot"),
    ("The Passion of Joan of Arc", 1928, "Carl Theodor Dreyer"),
    ("L.A. Confidential", 1997, "Curtis Hanson"),
    ("Kill Bill: Vol. 1", 2003, "Quentin Tarantino"),
    ("Jurassic Park", 1993, "Steven Spielberg"),
    ("Inside Out", 2015, "Pete Docter & Ronnie Del Carmen"),
    ("Indiana Jones and the Last Crusade", 1989, "Steven Spielberg"),
    ("Howl's Moving Castle", 2004, "Hayao Miyazaki"),
    ("Green Book", 2018, "Peter Farrelly"),
    ("Gone with the Wind", 1939, "Victor Fleming & George Cukor & Sam Wood"),
    ("Finding Nemo", 2003, "Andrew Stanton & Lee Unkrich"),
    ("The Secret in Their Eyes", 2009, "Juan José Campanella"),
    ("Pan's Labyrinth", 2006, "Guillermo del Toro"),
    ("Die Hard", 1988, "John McTiernan"),
    ("Dial M for Murder", 1954, "Alfred Hitchcock"),
    ("Dersu Uzala", 1975, "Akira Kurosawa"),
    ("Downfall", 2004, "Oliver Hirschbiegel"),
    ("Chinatown", 1974, "Roman Polanski"),
    ("Casino", 1995, "Martin Scorsese"),
    ("Batman Begins", 2005, "Christopher Nolan"),
    ("Children of Heaven", 1997, "Majid Majidi"),
    ("My Father and My Son", 2005, "Çagan Irmak"),
    ("All About Eve", 1950, "Joseph L. Mankiewicz"),
    ("A Beautiful Mind", 2001, "Ron Howard"),
    ("1917", 2019, "Sam Mendes"),
    ("Trainspotting", 1996, "Danny Boyle"),
    ("My Neighbor Totoro", 1988, "Hayao Miyazaki"),
    ("Three Billboards Outside Ebbing, Missouri", 2017, "Martin McDonagh"),
    ("The Wizard of Oz", 1939, "Victor Fleming & George Cukor & Mervyn LeRoy"),
    ("The Third Man", 1949, "Carol Reed"),
    ("The Terminator", 1984, "James Cameron"),
    ("The Sound of Music", 1965, "Robert Wise"),
    ("The Iron Giant", 1999, "Brad Bird"),
    ("The Help", 2011, "Tate Taylor"),
    ("The Grapes of Wrath", 1940, "John Ford"),
    ("The Grand Budapest Hotel", 2014, "Wes Anderson"),
    ("The Exorcist", 1973, "William Friedkin"),
    ("The Deer Hunter", 1978, "Michael Cimino"),
    ("The Big Lebowski", 1998, "Joel Coen & Ethan Coen"),
    ("The Best Years of Our Lives", 1946, "William Wyler"),
    ("Stand by Me", 1986, "Rob Reiner"),
    ("Spotlight", 2015, "Tom McCarthy"),
    ("Wild Strawberries", 1957, "Ingmar Bergman"),
    ("Memories of Murder", 2003, "Bong Joon Ho"),
    ("Rush", 2013, "Ron Howard"),
    ("Room", 2015, "Lenny Abrahamson"),
    ("Rocky", 1976, "John G. Avildsen"),
    ("Wild Tales", 2014, "Damián Szifron"),
    ("Rebecca", 1940, "Alfred Hitchcock"),
    ("Ratatouille", 2007, "Brad Bird & Jan Pinkava"),
    ("Prisoners", 2013, "Denis Villeneuve"),
    ("Platoon", 1986, "Oliver Stone"),
    ("Pirates of the Caribbean: The Curse of the Black Pearl", 2003, "Gore Verbinski"),
    ("Persona", 1966, "Ingmar Bergman"),
    ("On the Waterfront", 1954, "Elia Kazan"),
    ("Network", 1976, "Sidney Lumet"),
    ("Mr. Smith Goes to Washington", 1939, "Frank Capra"),
    ("Monsters, Inc.", 2001, "Pete Docter & David Silverman & Lee Unkrich"),
    ("Million Dollar Baby", 2004, "Clint Eastwood"),
    ("Mary and Max.", 2009, "Adam Elliot"),
    ("Mad Max: Fury Road", 2015, "George Miller"),
    ("Logan", 2017, "James Mangold"),
    ("The 400 Blows", 1959, "François Truffaut"),
    ("La haine", 1995, "Mathieu Kassovitz"),
    ("The Battle of Algiers", 1966, "Gillo Pontecorvo"),
    ("Klaus", 2019, "Sergio Pablos & Carlos Martínez López"),
    ("Jaws", 1975, "Steven Spielberg"),
    ("It Happened One Night", 1934, "Frank Capra"),
    ("Into the Wild", 2007, "Sean Penn"),
    ("In the Name of the Father", 1993, "Jim Sheridan"),
    ("How to Train Your Dragon", 2010, "Dean DeBlois & Chris Sanders"),
    ("Hotel Rwanda", 2004, "Terry George"),
    ("Harry Potter and the Deathly Hallows - Part 2", 2011, "David Yates"),
    ("Hacksaw Ridge", 2016, "Mel Gibson"),
    ("Hachi: A Dog's Tale", 2009, "Lasse Hallström"),
    ("Groundhog Day", 1993, "Harold Ramis"),
    ("Gran Torino", 2008, "Clint Eastwood"),
    ("Gone Girl", 2014, "David Fincher"),
    ("Gandhi", 1982, "Richard Attenborough"),
    ("Ford v Ferrari", 2019, "James Mangold"),
    ("Fargo", 1996, "Joel Coen & Ethan Coen"),
    ("Everything Everywhere All at Once", 2022, "Dan Kwan & Daniel Scheinert"),
    ("The Seventh Seal", 1957, "Ingmar Bergman"),
    ("Dead Poets Society", 1989, "Peter Weir"),
    ("Cool Hand Luke", 1967, "Stuart Rosenberg"),
    ("Catch Me If You Can", 2002, "Steven Spielberg"),
    ("Blade Runner", 1982, "Ridley Scott"),
    ("Ben-Hur", 1959, "William Wyler"),
    ("Before Sunset", 2004, "Richard Linklater"),
    ("Before Sunrise", 1995, "Richard Linklater"),
    ("Barry Lyndon", 1975, "Stanley Kubrick"),
    ("Amores perros", 2000, "Alejandro G. Iñárritu"),
    ("The Handmaiden", 2016, "Park Chan-wook"),
    ("12 Years a Slave", 2013, "Steve McQueen"),
    ("The Incredibles", 2004, "Brad Bird"),
    ("Life of Brian", 1979, "Terry Jones"),
    ("Aladdin", 1992, "Ron Clements & John Musker"),
]
