# -*- coding: utf-8 -*-
"""
The first 88 chemical elements.

Each entry: (atomic_number, symbol, english_name, latin_name)

Latin names use the New Latin (scientific) forms. For elements known since
antiquity the Latin name explains the symbol (e.g. Fe = Ferrum, Au = Aurum,
W = Wolframium). For elements coined in modern times the Latin form is the
Latinised international name (often identical to the English one).
"""

ELEMENTS = [
    (1,  "H",  "Hydrogen",     "Hydrogenium"),
    (2,  "He", "Helium",       "Helium"),
    (3,  "Li", "Lithium",      "Lithium"),
    (4,  "Be", "Beryllium",    "Beryllium"),
    (5,  "B",  "Boron",        "Borium"),
    (6,  "C",  "Carbon",       "Carboneum"),
    (7,  "N",  "Nitrogen",     "Nitrogenium"),
    (8,  "O",  "Oxygen",       "Oxygenium"),
    (9,  "F",  "Fluorine",     "Fluorum"),
    (10, "Ne", "Neon",         "Neon"),
    (11, "Na", "Sodium",       "Natrium"),
    (12, "Mg", "Magnesium",    "Magnesium"),
    (13, "Al", "Aluminium",    "Aluminium"),
    (14, "Si", "Silicon",      "Silicium"),
    (15, "P",  "Phosphorus",   "Phosphorus"),
    (16, "S",  "Sulfur",       "Sulphur"),
    (17, "Cl", "Chlorine",     "Chlorum"),
    (18, "Ar", "Argon",        "Argon"),
    (19, "K",  "Potassium",    "Kalium"),
    (20, "Ca", "Calcium",      "Calcium"),
    (21, "Sc", "Scandium",     "Scandium"),
    (22, "Ti", "Titanium",     "Titanium"),
    (23, "V",  "Vanadium",     "Vanadium"),
    (24, "Cr", "Chromium",     "Chromium"),
    (25, "Mn", "Manganese",    "Manganum"),
    (26, "Fe", "Iron",         "Ferrum"),
    (27, "Co", "Cobalt",       "Cobaltum"),
    (28, "Ni", "Nickel",       "Niccolum"),
    (29, "Cu", "Copper",       "Cuprum"),
    (30, "Zn", "Zinc",         "Zincum"),
    (31, "Ga", "Gallium",      "Gallium"),
    (32, "Ge", "Germanium",    "Germanium"),
    (33, "As", "Arsenic",      "Arsenicum"),
    (34, "Se", "Selenium",     "Selenium"),
    (35, "Br", "Bromine",      "Bromum"),
    (36, "Kr", "Krypton",      "Krypton"),
    (37, "Rb", "Rubidium",     "Rubidium"),
    (38, "Sr", "Strontium",    "Strontium"),
    (39, "Y",  "Yttrium",      "Yttrium"),
    (40, "Zr", "Zirconium",    "Zirconium"),
    (41, "Nb", "Niobium",      "Niobium"),
    (42, "Mo", "Molybdenum",   "Molybdaenum"),
    (43, "Tc", "Technetium",   "Technetium"),
    (44, "Ru", "Ruthenium",    "Ruthenium"),
    (45, "Rh", "Rhodium",      "Rhodium"),
    (46, "Pd", "Palladium",    "Palladium"),
    (47, "Ag", "Silver",       "Argentum"),
    (48, "Cd", "Cadmium",      "Cadmium"),
    (49, "In", "Indium",       "Indium"),
    (50, "Sn", "Tin",          "Stannum"),
    (51, "Sb", "Antimony",     "Stibium"),
    (52, "Te", "Tellurium",    "Tellurium"),
    (53, "I",  "Iodine",       "Iodum"),
    (54, "Xe", "Xenon",        "Xenon"),
    (55, "Cs", "Caesium",      "Caesium"),
    (56, "Ba", "Barium",       "Barium"),
    (57, "La", "Lanthanum",    "Lanthanum"),
    (58, "Ce", "Cerium",       "Cerium"),
    (59, "Pr", "Praseodymium", "Praseodymium"),
    (60, "Nd", "Neodymium",    "Neodymium"),
    (61, "Pm", "Promethium",   "Promethium"),
    (62, "Sm", "Samarium",     "Samarium"),
    (63, "Eu", "Europium",     "Europium"),
    (64, "Gd", "Gadolinium",   "Gadolinium"),
    (65, "Tb", "Terbium",      "Terbium"),
    (66, "Dy", "Dysprosium",   "Dysprosium"),
    (67, "Ho", "Holmium",      "Holmium"),
    (68, "Er", "Erbium",       "Erbium"),
    (69, "Tm", "Thulium",      "Thulium"),
    (70, "Yb", "Ytterbium",    "Ytterbium"),
    (71, "Lu", "Lutetium",     "Lutetium"),
    (72, "Hf", "Hafnium",      "Hafnium"),
    (73, "Ta", "Tantalum",     "Tantalum"),
    (74, "W",  "Tungsten",     "Wolframium"),
    (75, "Re", "Rhenium",      "Rhenium"),
    (76, "Os", "Osmium",       "Osmium"),
    (77, "Ir", "Iridium",      "Iridium"),
    (78, "Pt", "Platinum",     "Platinum"),
    (79, "Au", "Gold",         "Aurum"),
    (80, "Hg", "Mercury",      "Hydrargyrum"),
    (81, "Tl", "Thallium",     "Thallium"),
    (82, "Pb", "Lead",         "Plumbum"),
    (83, "Bi", "Bismuth",      "Bismuthum"),
    (84, "Po", "Polonium",     "Polonium"),
    (85, "At", "Astatine",     "Astatium"),
    (86, "Rn", "Radon",        "Radon"),
    (87, "Fr", "Francium",     "Francium"),
    (88, "Ra", "Radium",       "Radium"),
]
