# -*- coding: utf-8 -*-
"""
~250 of the most important events in world history.

Each entry: (event, date)

Date conventions:
  * BC years: "490 BC"; approximate ancient dates use "c." (e.g. "c. 1754 BC").
  * 1st-millennium AD years carry "AD" for clarity (e.g. "476 AD").
  * Where an event has a well-established exact date, the full date is given
    (e.g. "29 May 1453", "28 June 1914"); otherwise just the year.
  * A few drawn-out events use a span (e.g. "1347-1351").

Curated from well-established historical dates, spread across all eras and
regions (Near East, Greece, Rome, China, India, the Islamic world, the
Americas, Africa, and the modern world). Ordered chronologically.
"""

EVENTS = [
    # ── Prehistory & the Ancient Near East ───────────────────────────────────
    ("Neolithic Revolution — farming begins", "c. 10,000 BC"),
    ("First cities arise in Mesopotamia (Uruk)", "c. 4000 BC"),
    ("Invention of writing (cuneiform) in Sumer", "c. 3200 BC"),
    ("Unification of Upper and Lower Egypt", "c. 3100 BC"),
    ("Great Pyramid of Giza built", "c. 2560 BC"),
    ("Code of Hammurabi", "c. 1754 BC"),
    ("Eruption of Thera (Santorini)", "c. 1600 BC"),
    ("Reign of Akhenaten and early monotheism", "c. 1350 BC"),
    ("Battle of Kadesh (Egypt vs. Hittites)", "1274 BC"),
    ("Late Bronze Age collapse", "c. 1177 BC"),
    ("Traditional fall of Troy", "c. 1180 BC"),

    # ── Classical antiquity: Greece, Persia, India, China ────────────────────
    ("Traditional founding of Rome", "753 BC"),
    ("First Olympic Games", "776 BC"),
    ("Cyrus the Great founds the Persian Empire", "550 BC"),
    ("Roman Republic founded", "509 BC"),
    ("Buddha attains enlightenment (traditional)", "c. 528 BC"),
    ("Battle of Marathon", "490 BC"),
    ("Battles of Thermopylae and Salamis", "480 BC"),
    ("Golden Age of Athens under Pericles", "c. 450 BC"),
    ("Peloponnesian War begins", "431 BC"),
    ("Execution of Socrates", "399 BC"),
    ("Alexander the Great begins his conquests", "334 BC"),
    ("Alexander defeats Persia at Gaugamela", "331 BC"),
    ("Death of Alexander the Great", "323 BC"),
    ("Ashoka rules the Maurya Empire", "c. 268 BC"),
    ("Qin Shi Huang unifies China", "221 BC"),
    ("Hannibal crosses the Alps", "218 BC"),
    ("Han dynasty founded", "202 BC"),
    ("Rome destroys Carthage (Third Punic War)", "146 BC"),

    # ── Rome: Republic to Empire ─────────────────────────────────────────────
    ("Julius Caesar crosses the Rubicon", "49 BC"),
    ("Assassination of Julius Caesar", "15 March 44 BC"),
    ("Battle of Actium", "31 BC"),
    ("Augustus becomes first Roman Emperor", "27 BC"),
    ("Birth of Jesus of Nazareth", "c. 4 BC"),
    ("Crucifixion of Jesus", "c. 30 AD"),
    ("Destruction of Jerusalem and the Second Temple", "70 AD"),
    ("Eruption of Vesuvius destroys Pompeii", "79 AD"),
    ("Roman Empire at its greatest extent (Trajan)", "117 AD"),
    ("Edict of Milan legalizes Christianity", "313 AD"),
    ("Council of Nicaea", "325 AD"),
    ("Constantinople founded as Rome's new capital", "330 AD"),
    ("Roman Empire permanently split East and West", "395 AD"),

    # ── Late antiquity & the fall of Rome ────────────────────────────────────
    ("Visigoths under Alaric sack Rome", "410 AD"),
    ("Battle of Chalons halts Attila the Hun", "451 AD"),
    ("Vandals sack Rome", "455 AD"),
    ("Fall of the Western Roman Empire", "476 AD"),
    ("Hagia Sophia completed under Justinian", "537 AD"),
    ("Plague of Justinian", "541 AD"),

    # ── Rise of Islam & the early Middle Ages ────────────────────────────────
    ("Grand Canal of China completed", "609 AD"),
    ("Tang dynasty founded", "618 AD"),
    ("Muhammad's Hijra to Medina (start of Islamic calendar)", "622 AD"),
    ("Death of Muhammad", "632 AD"),
    ("Battle of Yarmouk — Arab conquest of the Levant", "636 AD"),
    ("Battle of Tours — Charles Martel halts Muslim advance", "732 AD"),
    ("Viking raid on Lindisfarne", "793 AD"),
    ("Charlemagne crowned Holy Roman Emperor", "25 December 800"),
    ("Treaty of Verdun divides the Carolingian Empire", "843 AD"),
    ("Leif Erikson reaches North America (Vinland)", "c. 1000 AD"),

    # ── The High & Late Middle Ages ──────────────────────────────────────────
    ("Great Schism splits Catholic and Orthodox churches", "1054"),
    ("Battle of Hastings — Norman conquest of England", "14 October 1066"),
    ("First Crusade begins", "1095"),
    ("Crusaders capture Jerusalem", "1099"),
    ("Angkor Wat built", "c. 1150"),
    ("Genghis Khan founds the Mongol Empire", "1206"),
    ("Magna Carta sealed", "15 June 1215"),
    ("Mongols sack Baghdad", "1258"),
    ("Marco Polo travels to China", "1271"),
    ("Mansa Musa's pilgrimage spreads Mali's fame", "1324"),
    ("Hundred Years' War begins", "1337"),
    ("Black Death devastates Europe", "1347-1351"),
    ("Ming dynasty founded", "1368"),
    ("Battle of Agincourt", "25 October 1415"),
    ("Joan of Arc lifts the siege of Orléans", "1429"),
    ("Gutenberg prints the Bible with movable type", "c. 1455"),
    ("Fall of Constantinople to the Ottomans", "29 May 1453"),
    ("End of the Hundred Years' War", "1453"),

    # ── Renaissance & the Age of Exploration ─────────────────────────────────
    ("Columbus reaches the Americas", "12 October 1492"),
    ("Fall of Granada completes the Reconquista", "1492"),
    ("Treaty of Tordesillas divides the New World", "1494"),
    ("Vasco da Gama reaches India by sea", "1498"),
    ("Leonardo paints the Mona Lisa", "c. 1503"),
    ("Luther's 95 Theses spark the Reformation", "31 October 1517"),
    ("Magellan's expedition circumnavigates the globe", "1519-1522"),
    ("Cortés conquers the Aztec Empire", "1521"),
    ("Pizarro conquers the Inca Empire", "1533"),
    ("Henry VIII breaks with Rome", "1534"),
    ("Copernicus publishes his heliocentric theory", "1543"),
    ("Council of Trent launches the Counter-Reformation", "1545"),
    ("Elizabeth I becomes Queen of England", "1558"),

    # ── The Early Modern world ───────────────────────────────────────────────
    ("English defeat the Spanish Armada", "1588"),
    ("English and Dutch East India Companies founded", "1600"),
    ("Jamestown — first permanent English colony in America", "1607"),
    ("Galileo's telescopic discoveries", "1610"),
    ("King James Bible published", "1611"),
    ("Thirty Years' War begins", "1618"),
    ("Pilgrims land at Plymouth (Mayflower)", "1620"),
    ("Taj Mahal construction begins", "1632"),
    ("English Civil War begins", "1642"),
    ("Peace of Westphalia ends the Thirty Years' War", "1648"),
    ("Execution of King Charles I", "30 January 1649"),
    ("Ottoman siege of Vienna repelled", "1683"),
    ("Newton publishes the Principia", "1687"),
    ("Glorious Revolution in England", "1688"),

    # ── The Enlightenment & the Age of Revolutions ───────────────────────────
    ("Act of Union creates Great Britain", "1707"),
    ("Seven Years' War begins", "1756"),
    ("Watt's improved steam engine drives the Industrial Revolution", "1769"),
    ("Boston Tea Party", "16 December 1773"),
    ("American Declaration of Independence", "4 July 1776"),
    ("Treaty of Paris ends the American Revolution", "1783"),
    ("US Constitution signed", "17 September 1787"),
    ("Storming of the Bastille — French Revolution begins", "14 July 1789"),
    ("Execution of King Louis XVI", "21 January 1793"),
    ("Haitian Revolution leads to independence", "1804"),
    ("Napoleon crowns himself Emperor", "2 December 1804"),
    ("Battle of Trafalgar", "21 October 1805"),
    ("Britain abolishes the slave trade", "1807"),
    ("Latin American wars of independence (Bolívar)", "c. 1810-1825"),
    ("Battle of Waterloo — Napoleon's final defeat", "18 June 1815"),
    ("Greek War of Independence begins", "1821"),

    # ── The 19th century ─────────────────────────────────────────────────────
    ("Stephenson's Rocket and the first railways", "1829"),
    ("Slavery abolished in the British Empire", "1833"),
    ("Victoria becomes Queen of the United Kingdom", "1837"),
    ("First Opium War", "1839"),
    ("Revolutions of 1848 and the Communist Manifesto", "1848"),
    ("California Gold Rush", "1849"),
    ("Commodore Perry forces open Japan", "1853"),
    ("Indian Rebellion against the British", "1857"),
    ("Darwin publishes On the Origin of Species", "1859"),
    ("Italian unification", "1861"),
    ("American Civil War begins", "12 April 1861"),
    ("Emancipation Proclamation", "1 January 1863"),
    ("Assassination of Abraham Lincoln", "14 April 1865"),
    ("Meiji Restoration modernizes Japan", "1868"),
    ("Suez Canal opens", "1869"),
    ("German unification under Bismarck", "1871"),
    ("Bell patents the telephone", "1876"),
    ("Berlin Conference and the Scramble for Africa", "1884"),
    ("Benz builds the first automobile", "1885"),
    ("Eiffel Tower completed", "1889"),

    # ── The early 20th century & World War I ─────────────────────────────────
    ("Wright brothers' first powered flight", "17 December 1903"),
    ("Russo-Japanese War", "1904"),
    ("Einstein's theory of special relativity", "1905"),
    ("Ford's Model T and the moving assembly line", "1908"),
    ("Sinking of the Titanic", "15 April 1912"),
    ("Assassination of Archduke Franz Ferdinand", "28 June 1914"),
    ("World War I begins", "28 July 1914"),
    ("Russian Revolution — Bolsheviks seize power", "7 November 1917"),
    ("Armistice ends World War I", "11 November 1918"),
    ("Spanish flu pandemic", "1918"),
    ("Treaty of Versailles", "28 June 1919"),
    ("Mussolini's March on Rome", "1922"),
    ("Soviet Union founded", "1922"),

    # ── The interwar years & World War II ────────────────────────────────────
    ("Wall Street Crash begins the Great Depression", "29 October 1929"),
    ("Gandhi's Salt March", "1930"),
    ("Hitler becomes Chancellor of Germany", "30 January 1933"),
    ("Mao's Long March", "1934"),
    ("Spanish Civil War begins", "1936"),
    ("Kristallnacht", "9 November 1938"),
    ("Germany invades Poland — World War II begins", "1 September 1939"),
    ("Fall of France and the Battle of Britain", "1940"),
    ("Attack on Pearl Harbor", "7 December 1941"),
    ("The Holocaust and the Wannsee Conference", "1942"),
    ("Battle of Stalingrad ends", "2 February 1943"),
    ("D-Day — Allied landings in Normandy", "6 June 1944"),
    ("Victory in Europe (VE Day)", "8 May 1945"),
    ("Atomic bombing of Hiroshima", "6 August 1945"),
    ("Japan surrenders — World War II ends", "2 September 1945"),
    ("United Nations founded", "24 October 1945"),

    # ── The Cold War & decolonization ────────────────────────────────────────
    ("Indian independence and Partition", "15 August 1947"),
    ("Founding of the State of Israel", "14 May 1948"),
    ("Berlin Airlift", "1948"),
    ("NATO founded", "1949"),
    ("Mao founds the People's Republic of China", "1 October 1949"),
    ("Korean War begins", "1950"),
    ("Discovery of the DNA double helix", "1953"),
    ("Suez Crisis", "1956"),
    ("Sputnik launched — the Space Age begins", "4 October 1957"),
    ("Cuban Revolution brings Castro to power", "1959"),
    ("Berlin Wall built", "13 August 1961"),
    ("Cuban Missile Crisis", "October 1962"),
    ("Assassination of John F. Kennedy", "22 November 1963"),
    ("US Civil Rights Act", "1964"),
    ("Chinese Cultural Revolution begins", "1966"),
    ("Assassination of Martin Luther King Jr.", "4 April 1968"),
    ("Apollo 11 — first humans on the Moon", "20 July 1969"),

    # ── The late 20th century ────────────────────────────────────────────────
    ("Watergate scandal", "1972"),
    ("OPEC oil crisis", "1973"),
    ("Fall of Saigon ends the Vietnam War", "30 April 1975"),
    ("Iranian Revolution", "1979"),
    ("Soviet invasion of Afghanistan", "1979"),
    ("Chernobyl nuclear disaster", "26 April 1986"),
    ("Tim Berners-Lee invents the World Wide Web", "1989"),
    ("Tiananmen Square protests", "4 June 1989"),
    ("Fall of the Berlin Wall", "9 November 1989"),
    ("German reunification", "3 October 1990"),
    ("Dissolution of the Soviet Union", "26 December 1991"),
    ("End of apartheid — Mandela elected President", "1994"),
    ("Rwandan genocide", "1994"),
    ("Hong Kong returned to China", "1 July 1997"),

    # ── The 21st century ─────────────────────────────────────────────────────
    ("September 11 attacks", "11 September 2001"),
    ("Euro enters circulation", "1 January 2002"),
    ("Iraq War begins", "2003"),
    ("Indian Ocean earthquake and tsunami", "26 December 2004"),
    ("Global Financial Crisis", "2008"),
    ("Barack Obama elected US President", "4 November 2008"),
    ("Apple releases the iPhone", "29 June 2007"),
    ("Arab Spring begins", "2010"),
    ("Death of Osama bin Laden", "2 May 2011"),
    ("Brexit referendum", "23 June 2016"),
    ("COVID-19 declared a pandemic", "11 March 2020"),
    ("Russia invades Ukraine", "24 February 2022"),
]
