# -*- coding: utf-8 -*-
"""
Famous inventions across history — from the Stone Age to the 21st century.

Each entry: (invention, inventor, year)

Sourcing & conventions (see the deck summary for the full rationale):
  * Dates use "c." for approximate/contested dates. Deep-prehistory dates are
    given as broad approximations (e.g. "c. 1,000,000 BC").
  * For inventions with no known individual, the inventor field credits the
    originating culture or people (e.g. "Sumerians", "Han dynasty China").
  * For inventions with multiple or disputed claimants, the most conventionally
    credited person(s) are listed; priority is often debated by historians.
  * The year is the most commonly cited one (first prototype, patent, or public
    demonstration), even when development spanned years.
"""

INVENTIONS = [
    # ── Prehistory & the Ancient world ───────────────────────────────────────
    ("Stone tools",            "Early hominins (Homo habilis)",          "c. 2.6 million BC"),
    ("Control of fire",        "Homo erectus",                           "c. 1,000,000 BC"),
    ("Spear",                  "Early humans",                           "c. 300,000 BC"),
    ("Bow and arrow",          "Prehistoric humans",                     "c. 60,000 BC"),
    ("Sewing needle",          "Prehistoric humans",                     "c. 60,000 BC"),
    ("Flute (musical instrument)", "Paleolithic Europeans",              "c. 40,000 BC"),
    ("Pottery",                "Ancient East Asians (China)",            "c. 18,000 BC"),
    ("Agriculture",            "Neolithic peoples (Fertile Crescent)",   "c. 10,000 BC"),
    ("Brick",                  "Ancient Near East",                      "c. 9,000 BC"),
    ("Wheel",                  "Ancient Mesopotamia",                    "c. 3,500 BC"),
    ("Plough",                 "Ancient Mesopotamia",                    "c. 3,500 BC"),
    ("Writing",                "Sumerians",                              "c. 3,200 BC"),
    ("Bronze",                 "Ancient Mesopotamia",                    "c. 3,300 BC"),
    ("Papyrus",                "Ancient Egyptians",                      "c. 3,000 BC"),
    ("Sundial",                "Ancient Egyptians",                      "c. 1,500 BC"),
    ("Glass",                  "Ancient Mesopotamia / Egypt",            "c. 1,500 BC"),
    ("Iron smelting",          "Hittites",                               "c. 1,200 BC"),
    ("Alphabet",               "Phoenicians",                            "c. 1,050 BC"),
    ("Coinage",                "Lydians",                                "c. 600 BC"),
    ("Crossbow",               "Ancient China",                          "c. 600 BC"),
    ("Aqueduct",               "Ancient Romans",                         "312 BC"),
    ("Archimedes' screw",      "Archimedes",                             "c. 250 BC"),
    ("Watermill",              "Ancient Greeks",                         "c. 250 BC"),
    ("Astrolabe",              "Ancient Greek astronomers (Hipparchus)", "c. 150 BC"),
    ("Concrete",               "Ancient Romans",                         "c. 200 BC"),

    # ── Classical & Medieval ─────────────────────────────────────────────────
    ("Paper",                  "Cai Lun (Han dynasty China)",            "c. 105 AD"),
    ("Compass (magnetic)",     "Han dynasty China",                      "c. 200 BC"),
    ("Seismometer",            "Zhang Heng",                             "132 AD"),
    ("Woodblock printing",     "Tang dynasty China",                     "c. 700 AD"),
    ("Gunpowder",              "Tang dynasty Chinese alchemists",        "c. 850 AD"),
    ("Spinning wheel",         "India / China",                          "c. 1000"),
    ("Movable-type printing",  "Bi Sheng (Song dynasty China)",          "c. 1040"),
    ("Eyeglasses",             "Italy (attributed to Salvino D'Armate)", "c. 1286"),
    ("Mechanical clock",       "Medieval Europe",                        "c. 1300"),
    ("Hourglass",              "Medieval Europe",                        "c. 1300"),
    ("Blast furnace",          "China / Medieval Europe",                "c. 1300"),

    # ── Renaissance & the Scientific Revolution ──────────────────────────────
    ("Printing press",         "Johannes Gutenberg",                     "c. 1440"),
    ("Pocket watch",           "Peter Henlein",                          "c. 1510"),
    ("Mercator map projection","Gerardus Mercator",                      "1569"),
    ("Microscope",             "Zacharias Janssen",                      "c. 1590"),
    ("Thermometer",            "Galileo Galilei",                        "c. 1593"),
    ("Telescope",              "Hans Lippershey",                        "1608"),
    ("Submarine",              "Cornelius Drebbel",                      "1620"),
    ("Slide rule",             "William Oughtred",                       "1622"),
    ("Mechanical calculator",  "Blaise Pascal",                          "1642"),
    ("Barometer",              "Evangelista Torricelli",                 "1643"),
    ("Vacuum pump",            "Otto von Guericke",                      "1650"),
    ("Pendulum clock",         "Christiaan Huygens",                     "1656"),
    ("Pressure cooker",        "Denis Papin",                            "1679"),

    # ── 18th century & the early Industrial Revolution ───────────────────────
    ("Piano",                  "Bartolomeo Cristofori",                  "c. 1700"),
    ("Steam engine (atmospheric)", "Thomas Newcomen",                    "1712"),
    ("Mercury thermometer",    "Daniel Gabriel Fahrenheit",              "1714"),
    ("Sextant",                "John Hadley",                            "1731"),
    ("Flying shuttle",         "John Kay",                               "1733"),
    ("Marine chronometer",     "John Harrison",                          "1761"),
    ("Spinning jenny",         "James Hargreaves",                       "1764"),
    ("Improved steam engine",  "James Watt",                             "1769"),
    ("Water frame",            "Richard Arkwright",                      "1769"),
    ("Hot air balloon",        "Montgolfier brothers",                   "1783"),
    ("Parachute",              "Louis-Sébastien Lenormand",              "1783"),
    ("Bifocals",               "Benjamin Franklin",                      "1784"),
    ("Power loom",             "Edmund Cartwright",                      "1785"),
    ("Cotton gin",             "Eli Whitney",                            "1793"),
    ("Smallpox vaccine",       "Edward Jenner",                          "1796"),
    ("Electric battery",       "Alessandro Volta",                       "1800"),

    # ── 19th century ─────────────────────────────────────────────────────────
    ("Steam locomotive",       "Richard Trevithick",                     "1804"),
    ("Steamboat",              "Robert Fulton",                          "1807"),
    ("Food canning",           "Nicolas Appert",                         "1810"),
    ("Stethoscope",            "René Laennec",                           "1816"),
    ("Bicycle",                "Karl von Drais",                         "1817"),
    ("Electric motor",         "Michael Faraday",                        "1821"),
    ("Braille",                "Louis Braille",                          "1824"),
    ("Portland cement",        "Joseph Aspdin",                          "1824"),
    ("Photography",            "Nicéphore Niépce",                       "1826"),
    ("Friction match",         "John Walker",                            "1826"),
    ("Electric generator (dynamo)", "Michael Faraday",                   "1831"),
    ("Refrigeration",          "Jacob Perkins",                          "1834"),
    ("Revolver",               "Samuel Colt",                            "1836"),
    ("Electric telegraph",     "Samuel Morse",                           "1837"),
    ("Analytical Engine (programmable computer)", "Charles Babbage",     "1837"),
    ("Vulcanized rubber",      "Charles Goodyear",                       "1839"),
    ("Saxophone",              "Adolphe Sax",                            "1846"),
    ("Sewing machine",         "Elias Howe",                             "1846"),
    ("Anesthesia (ether)",     "William T. G. Morton",                   "1846"),
    ("Safety elevator",        "Elisha Otis",                            "1852"),
    ("Pasteurization",         "Louis Pasteur",                          "1864"),
    ("Dynamite",               "Alfred Nobel",                           "1867"),
    ("Typewriter",             "Christopher Latham Sholes",              "1868"),
    ("Telephone",              "Alexander Graham Bell",                  "1876"),
    ("Four-stroke engine",     "Nikolaus Otto",                          "1876"),
    ("Phonograph",             "Thomas Edison",                          "1877"),
    ("Incandescent light bulb","Thomas Edison",                          "1879"),
    ("Machine gun (Maxim gun)","Hiram Maxim",                            "1884"),
    ("Steam turbine",          "Charles Parsons",                        "1884"),
    ("Automobile",             "Karl Benz",                              "1885"),
    ("Rabies vaccine",         "Louis Pasteur",                          "1885"),
    ("Dishwasher",             "Josephine Cochrane",                     "1886"),
    ("Pneumatic tire",         "John Boyd Dunlop",                       "1888"),
    ("Alternating-current motor", "Nikola Tesla",                        "1888"),
    ("Roll-film camera (Kodak)", "George Eastman",                       "1888"),
    ("Zipper",                 "Whitcomb Judson",                        "1893"),
    ("Radio",                  "Guglielmo Marconi",                      "1895"),
    ("X-ray imaging",          "Wilhelm Röntgen",                        "1895"),
    ("Motion picture (cinematograph)", "Lumière brothers",              "1895"),
    ("Diesel engine",          "Rudolf Diesel",                          "1897"),
    ("Aspirin",                "Felix Hoffmann (Bayer)",                 "1897"),
    ("Cathode-ray tube",       "Karl Ferdinand Braun",                   "1897"),

    # ── 20th century ─────────────────────────────────────────────────────────
    ("Air conditioning",       "Willis Carrier",                         "1902"),
    ("Airplane",               "Wright brothers",                        "1903"),
    ("Vacuum tube (diode)",    "John Ambrose Fleming",                   "1904"),
    ("Gasoline tractor",       "Benjamin Holt",                          "1904"),
    ("Bakelite (plastic)",     "Leo Baekeland",                          "1907"),
    ("Moving assembly line",   "Henry Ford",                             "1913"),
    ("Military tank",          "Ernest Swinton (British Army)",          "1916"),
    ("Insulin",                "Frederick Banting & Charles Best",       "1921"),
    ("Liquid-fuel rocket",     "Robert Goddard",                         "1926"),
    ("Television",             "Philo Farnsworth",                       "1927"),
    ("Penicillin",             "Alexander Fleming",                      "1928"),
    ("FM radio",               "Edwin Armstrong",                        "1933"),
    ("Nylon",                  "Wallace Carothers (DuPont)",             "1935"),
    ("Radar",                  "Robert Watson-Watt",                     "1935"),
    ("Jet engine",             "Frank Whittle",                          "1937"),
    ("Ballpoint pen",          "László Bíró",                            "1938"),
    ("Photocopier (xerography)", "Chester Carlson",                      "1938"),
    ("Teflon",                 "Roy Plunkett",                           "1938"),
    ("Helicopter",             "Igor Sikorsky",                          "1939"),
    ("Nuclear reactor",        "Enrico Fermi",                           "1942"),
    ("Electronic computer (ENIAC)", "John Mauchly & J. Presper Eckert",  "1945"),
    ("Microwave oven",         "Percy Spencer",                          "1945"),
    ("Atomic bomb",            "Manhattan Project (J. R. Oppenheimer)",  "1945"),
    ("Transistor",             "Bardeen, Brattain & Shockley",           "1947"),
    ("Velcro",                 "George de Mestral",                      "1948"),
    ("Barcode",                "Norman Joseph Woodland",                 "1952"),
    ("Hydrogen bomb",          "Edward Teller & Stanislaw Ulam",         "1952"),
    ("Solar cell",             "Bell Labs (Chapin, Fuller & Pearson)",   "1954"),
    ("Polio vaccine",          "Jonas Salk",                             "1955"),
    ("Integrated circuit",     "Jack Kilby & Robert Noyce",              "1958"),
    ("Implantable pacemaker",  "Wilson Greatbatch",                      "1958"),
    ("Laser",                  "Theodore Maiman",                        "1960"),
    ("Contraceptive pill",     "Gregory Pincus & Carl Djerassi",         "1960"),
    ("Light-emitting diode (LED)", "Nick Holonyak",                      "1962"),
    ("Computer mouse",         "Douglas Engelbart",                      "1964"),
    ("Kevlar",                 "Stephanie Kwolek",                       "1965"),
    ("Optical fiber (communications)", "Charles Kao",                    "1966"),
    ("Email",                  "Ray Tomlinson",                          "1971"),
    ("Microprocessor (Intel 4004)", "Ted Hoff (Intel)",                  "1971"),
    ("Mobile phone",           "Martin Cooper (Motorola)",               "1973"),
    ("Internet (TCP/IP)",      "Vint Cerf & Bob Kahn",                   "1974"),
    ("Digital camera",         "Steven Sasson (Kodak)",                  "1975"),
    ("Personal computer (Altair 8800)", "Ed Roberts (MITS)",            "1975"),
    ("MRI scanner",            "Raymond Damadian & Paul Lauterbur",      "1977"),
    ("GPS",                    "U.S. Department of Defense",             "1978"),
    ("In vitro fertilization (IVF)", "Robert Edwards & Patrick Steptoe", "1978"),
    ("3D printing",            "Chuck Hull",                             "1984"),
    ("DNA fingerprinting",     "Alec Jeffreys",                          "1984"),
    ("Lithium-ion battery",    "John Goodenough & Akira Yoshino",        "1985"),
    ("World Wide Web",         "Tim Berners-Lee",                        "1989"),
    ("Bluetooth",              "Jaap Haartsen (Ericsson)",               "1994"),
    ("Wi-Fi",                  "IEEE / John O'Sullivan (CSIRO)",         "1997"),

    # ── 21st century ─────────────────────────────────────────────────────────
    ("Smartphone (iPhone)",    "Apple (Steve Jobs et al.)",             "2007"),
    ("CRISPR gene editing",    "Jennifer Doudna & Emmanuelle Charpentier","2012"),
    ("Reusable orbital rocket","SpaceX",                                 "2015"),
    ("mRNA vaccine",           "Katalin Karikó & Drew Weissman",         "2020"),
]
